### ISSUE TITLE
Cannot retrieve latest version

### ISSUE THREAD

**Issue by marky291** [faustbrian/laravel-reportable#30]
<img width="1386" alt="Screenshot 2019-09-30 at 20 22 38" src="https://user-images.githubusercontent.com/5384515/65909258-1fe77800-e3c0-11e9-82bf-ee6af047ce46.png">
<img width="234" alt="Screenshot 2019-09-30 at 20 22 33" src="https://user-images.githubusercontent.com/5384515/65909259-1fe77800-e3c0-11e9-8197-1e80baa9974f.png">

**Comment by marky291** [comment]
composer update on ^3.2 also wont pull it.

**Comment by faustbrian** [comment]
https://packagist.org/packages/artisanry/reportable
